---
apiVersion: batch/v1
kind: Job
metadata:
  name: shell-operator
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: shell-operator
        image: piggywave/shell-operator:v1
        imagePullPolicy: Never