---
apiVersion: v1
kind: Pod
metadata:
  name: shell-operator
spec:
  containers:
  - name: shell-operator
    image: piggywave/shell-operator:v1
    imagePullPolicy: Never
    env:
    - name: DEBUG_KEEP_TMP_FILES
      value: "no"
    ports:
    - containerPort: 9115